### 服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
### 网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理
zuul:
  routes:
    api-a:
      path: /wusd-a/**
      serviceId: wusd_a
    api-b:
      path: /wusd-b/**
      serviceId: wusd_b
