spring:
  datasource:
    test1:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: wusd123..
      driver-class-name: com.mysql.jdbc.Driver
    test2:
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: wusd123..
      driver-class-name: com.mysql.jdbc.Driver
